# Generated by Django 2.2.6 on 2019-10-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsongs',
            name='is_curr_song',
            field=models.BooleanField(default=False, verbose_name='Is Current Song'),
        ),
    ]
