# Generated by Django 2.2.6 on 2019-12-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191125_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionsongs',
            name='is_curr_song',
        ),
        migrations.RemoveField(
            model_name='sessionsongs',
            name='user',
        ),
        migrations.AddField(
            model_name='sessions',
            name='session_pass',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Session Password'),
        ),
        migrations.AddField(
            model_name='sessionsongs',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='Added By User'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='owner',
            field=models.CharField(max_length=20, null=True, verbose_name='Session Owner'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Session ID'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='currentsongs',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Sessions', verbose_name='Session ID'),
        ),
        migrations.AddField(
            model_name='currentsongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.SessionSongs', verbose_name='Song ID'),
        ),
    ]
