# Generated by Django 2.2.6 on 2019-12-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191204_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='session_pass',
        ),
        migrations.AddField(
            model_name='sessions',
            name='session_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Session Password'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='owner',
            field=models.CharField(max_length=255, null=True, verbose_name='Session Owner'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='session_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Session Name'),
        ),
    ]
