# Generated by Django 2.2.6 on 2019-12-05 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191204_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SessionSongs', verbose_name='Song ID'),
        ),
        migrations.AlterField(
            model_name='sessionsongs',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='Added By User'),
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('message_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Message ID')),
                ('message', models.TextField(blank=True, verbose_name='Chat Message')),
                ('username', models.CharField(max_length=255, null=True, verbose_name='Added By User')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sessions', verbose_name='Session ID')),
            ],
        ),
    ]
